### ISSUE TITLE
Add multiple items

### ISSUE THREAD

**Issue by KeithViking** [umbraco/Umbraco.Commerce.Checkout#13]
Hi

I have a page which shows 6 products. 

Instead of adding each product individually is there a way to add them all in one attempt in the addProduct method? I don't want to for each the Add function.

Looking at the overloads methods I can't find anything to add these products in this manner but thought to see if this could be added in future if not already available?

**Comment by mattbrailsford** [comment]
You need to call `AddProduct` for each product you wish to add, but these can all be done within the same unit of work to ensure they all occur or non occur.

**Comment by KeithViking** [comment]
Hi @mattbrailsford 

I'll post to the correct channel. 

Just to clarify, in one unit of work addProduct only takes in one product and not list?

I don't want to add a for loop around this. So this isn't possible to send a list of items?

**Comment by mattbrailsford** [comment]
that's correct, you need to call `AddProduct` per product you wish to add. If you really need the latter, you could probably create an extension method

```
public static class OrderExtensions
{
    public static void AddProducts(this Order order, string[] productReferences)
        => productReferences.ForEach(pr => order.AddProduct(pr, 1);
}
