### ISSUE TITLE
Theme color - "Continue" button color in checkout steps

### ISSUE THREAD

**Issue by Ramya-Devendiran** [umbraco/Umbraco.Commerce.Checkout#3]
Umbraco Commerce Checkout version - 12.0.0 and Umbraco version 12.2.0
Theme color (uccThemeColor) "black" is not working. bg-black css is missing. Other colors are working.
How to make new theme colors work?

**Comment by mattbrailsford** [comment]
Looks like we might need to update the safe list to include this https://github.com/umbraco/Umbraco.Commerce.Checkout/blob/main/src/Umbraco.Commerce.Checkout/Client/tailwind.config.js#L10

**Comment by Ramya-Devendiran** [comment]
Thanks for the quick reply. Your solution would fix black backgroud color. Thats great. 
Is it customizable to add new color theme to the data type "[Umbraco Commerce Checkout] Theme Color Picker"

**Comment by Ramya-Devendiran** [comment]
ok. Can you guide me to create a custom build?

**Comment by mattbrailsford** [comment]
You should be able to fork the repo, make the changes you need and then in the root of the solution run `dotnet pack Umbraco.Commerce.Checkout.sln --configuration Release --output artifacts` which should compile a custom NuGet package into an artifacts folder. You can then followin instructions here for using the artifacts folder as a local NuGet feed https://learn.microsoft.com/en-us/nuget/hosting-packages/local-feeds

**Comment by Ramya-Devendiran** [comment]
Thanks a lot for support.

**Comment by umbracotrd** [comment]
Fixed on `10.0.3`, `12.0.2` and `13.1.1`.
