### ISSUE TITLE
Label for shipping information and billing information does not break words

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Commerce.Checkout#4]
This issue is seen on the "Review" step. 
On the demo store, it says "Shipping information" and "Billing information". 
It looks like the space in the label allows for an automatic break.
But in other languages, there might not be a space. 
"Shipping information" translates to "Leveringsinformation" in danish, 
No space in the label, so the UI breaks on small screens. 
Trying to force a break with `&shy;` is ignored as well. 

In some way, the words should be able to break.

Nice UI with a short label
![image](https://github.com/umbraco/Umbraco.Commerce.Checkout/assets/6904597/b8ee7198-3c1a-4193-9a24-c06c7267a922)

Broken UI with a long label
![image](https://github.com/umbraco/Umbraco.Commerce.Checkout/assets/6904597/c2b6f2dc-8d83-41ab-9aee-563bda88e682)

**Comment by umbracotrd** [comment]
I'm enabling word break and wrap the layout of `UmbracoCommerceCheckoutOrderInfo.cshtml` into one column for mobile screen. Even so, bear in mind that we didn't not test the package on mobile view thoroughly, so, there maybe other places suffer from the same issue.

![image](https://github.com/umbraco/Umbraco.Commerce.Checkout/assets/145000730/7d894622-3ecb-42e6-9556-9c772a54dcf9)

**Comment by umbracotrd** [comment]
Fixed on `10.0.3`, `12.0.2` and `13.1.1`.
