### ISSUE TITLE
How to pass data to checkout?

### ISSUE THREAD

**Issue by JamiePattison** [umbraco/Umbraco.Commerce.Checkout#7]
In the older versions I believe it wasn't possible to pass data such as email from Umbraco.Commerce to the landing page for the checkout.

Is it possible to do this with this version @mattbrailsford ? If yes any examples to follow? Or is it a matter of forking this and making changes myself?

**Comment by mattbrailsford** [comment]
The checkout package just reads and sets properties on the order. If you set these before hitting the checkout it will load them and show them in the fields.

**Comment by JamiePattison** [comment]
> The checkout package just reads and sets properties on the order. If you set these before hitting the checkout it will load them and show them in the fields.
> 
> See code here for the properties it uses https://github.com/umbraco/Umbraco.Commerce.Checkout/blob/main/src/Umbraco.Commerce.Checkout/Web/Controllers/UmbracoCommerceCheckoutSurfaceController.cs#L115

Hi @mattbrailsford 

The first and last name property alias seem to be incorrect. 

I've tried billingAddressFirstname, Firstname, firstName and other combinations but these don't seem to find the correct property alias. 

Please could you confirm the correct alias?

**Comment by mattbrailsford** [comment]
it should be looking for an order level property names 'firstName`

**Comment by JamiePattison** [comment]
> it should be looking for an order level property names 'firstName`

@mattbrailsford I have already attempted that but that didn't work. I even downloaded the project and looked at the constant value which didn't work (firstName). Is there any way I could find this out as I assume this is the alias that's been setup in Umbraco?

**Comment by mattbrailsford** [comment]
What code are you using to set the property?

**Comment by mattbrailsford** [comment]
Sorry, I want to see the entire code you are using to write the properties to the order.

**Comment by JamiePattison** [comment]
[HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateUmbracoFormRouteString]
        public IActionResult UpdateCustomerInfo(UccUpdateOrderInformationDto model)
        {
            try
            {
                
                _commerceApi.Uow.Execute(uow =>
                {
                    var store = CurrentPage.GetStore();
                    var order = _commerceApi.GetCurrentOrder(store.Id)
                        .AsWritable(uow)
                        .SetProperties(new Dictionary<string, string>
                        {
                            { "email", model.Email },
                            { "marketingOptIn", model.MarketingOptIn ? "1" : "0" },

                            {"firstName", model.BillingAddress.FirstName },
                            { "lastName", model.BillingAddress.LastName },
                            { "billingAddressLine1", model.BillingAddress.Line1 },
                            { "billingAddressLine2", model.BillingAddress.Line2 },
                            { "billingCity", model.BillingAddress.City },
                            { "billingZipCode", model.BillingAddress.ZipCode },
                            { "billingTelephone", model.BillingAddress.Telephone },
                            { "comments", model.Comments },
                            { "ipAddress", GetIPAddress() }
                        })
                        .SetPaymentCountryRegion(model.BillingAddress

                        _commerceApi.SaveOrder(order);
                        uow.Complete();
}

All the other properties come through fine just first and last name are the problematic ones

**Comment by mattbrailsford** [comment]
Looks like it should all be ok to me 🤔

Do you have any other notification handlers that could be interfering?
