### ISSUE TITLE
Zero based products at checkout

### ISSUE THREAD

**Issue by JamiePattison** [umbraco/Umbraco.Commerce.Checkout#8]
Hi

I have a few zero priced products. I also have a few paid for products. 

I add zero based payment provider in Umbraco. 

Add 4 products (or even 1)  to my cart where the total value is 0, go to checkout and I'm prompted with a Payment Method screen. I was expecting this step to be hidden as there's nothing to pay for 

I add all paid for products and get to the checkout, see the zero based payment provider as an option. I was expecting this to be hidden so they pay for the products.

Have I configured this incorrectly as I thought as long as the total value was 0 no payment method is applicable and if there are paid for products the system would hide the zero based provider as they need to be paid for and display only the options I have set to take payment for? 

Issue 2

When clicking I agree and accept T&C's to make a payment, is it possible to modify/update that step so it also checks the amount of stock remaining (in case the stock hits 0 as the customer has been at the checkout for a few minutes and someone else has taken the last item)

**Comment by mattbrailsford** [comment]
1. What is the alias of your zero value payment method configuration? it must be `zeroValue` exactly for it to get picked up by Checkout.

2. You can set up a validation event handler to do this. See the docs here for an example https://docs.umbraco.com/umbraco-commerce/how-to-guides/limit-orderline-quantity

**Comment by JamiePattison** [comment]
> 1. What is the alias of your zero value payment method configuration? it must be `zeroValue` exactly for it to get picked up by Checkout.
> 2. You can set up a validation event handler to do this. See the docs here for an example https://docs.umbraco.com/umbraco-commerce/how-to-guides/limit-orderline-quantity

1. In Umbraco, under Payment Methods I created a new Payment Method. Called it 'No Payment' and selected Zero Value. Is that what you mean? When I select that provider I can see zeroValue listed under Info (payment provider alias)
2. Ok let me look into that again as it doesn't seem to fire when I click to make payment.

**Comment by mattbrailsford** [comment]
You need this value to be set to the exact value of `zeroValue`

![image](https://github.com/umbraco/Umbraco.Commerce.Checkout/assets/527305/c8fe6807-0370-4b7c-8ff2-27ec56fa7d36)

**Comment by JamiePattison** [comment]
Let me try that out.... Just so I understand, what would this achieve? Would it differentiate between 0 total prices and show payment providers if the total is more than?

**Comment by JamiePattison** [comment]
I compared my setup against Blendid and it's pretty much the same for the checkout. 

For some reason shipping is missing in the breadcrumbs (I've decided to undo any custom changes until I see it working) and even after republishing the entire site.

The landing URL is site/checkout and I installed checkout on the root of the site. Any logs I could look at to see what might be going on under the hood? 

Thanks

**Comment by mattbrailsford** [comment]
Can you try setting the alias to `uccZeroValue`?

**Comment by JamiePattison** [comment]
> Can you try setting the alias to `uccZeroValue`?

That seems to have resolved it 👍. Thank you. 

Is there any documentation that I could refer to for reference? I was looking into the code but it would have taken me a while to get to this stage.

**Comment by mattbrailsford** [comment]
Not really on this one. The zero value payment method should get auto setup when the package is installed so something must have been off for it not to generate it. Really, you shouldn't have had to create the payment method yourself and so hence why there wouldn't be any docs telling you to do so.
